### ISSUE TITLE
Feature request: Allow Manual Reminder(s) Settings

### ISSUE THREAD

**Issue by njobrien1006** [allenporter/gcal_sync#239] opened 2023-04-29 17:47 UTC
I'm in search of a way to add All-Day Calander Events to my Google Calendar with appropriate Reminders.  With very specific G.Cal and Iphone settings I can get desired results (with an additional manual step). Within HA, All-Day Events alarm at `Event Notifications` time and not `All-Day Event Notifications`.

Searching around the WWW I found that the [API](https://developers.google.com/calendar/api/guides/create-events#python) supports it and ventured into HA to make the change VIA custom_components. Only to find the underlying dependency.

According to some forums, it seems this is a known behavior that the allow-day event notifications doesn't work outside of the Google environment. Which leaves defining non-default reminders.

Is there anyway the reminders API portion could be implemented?

```
event = {
  'summary': 'Google I/O 2015',
  'location': '800 Howard St., San Francisco, CA 94103',
  'description': 'A chance to hear more about Google\'s developer products.',
  'start': {
    'dateTime': '2015-05-28T09:00:00-07:00',
    'timeZone': 'America/Los_Angeles',
  },
  'end': {
    'dateTime': '2015-05-28T17:00:00-07:00',
    'timeZone': 'America/Los_Angeles',
  },
  'recurrence': [
    'RRULE:FREQ=DAILY;COUNT=2'
  ],
  'attendees': [
    {'email': 'lpage@example.com'},
    {'email': 'sbrin@example.com'},
  ],
  'reminders': {
    'useDefault': False,
    'overrides': [
      {'method': 'email', 'minutes': 24 * 60},
      {'method': 'popup', 'minutes': 10},
    ],
  },
}
```

**Comment by allenporter** [comment] 2023-04-29 21:32
Can you explain a bit more about the use case of what you are trying to accomplish? (e.g. the actual real world scenario). Thanks, its helpful to have additional context to understand the implementation goals.

**Comment by allenporter** [comment] 2023-04-29 21:55
This has been released with 4.2.0 https://github.com/allenporter/gcal_sync/releases/tag/4.2.0

**Closed by allenporter** 2023-04-29 21:55 UTC

**Comment by njobrien1006** [comment] 2023-04-30 13:06
Thank you for your prompt response.

The use case is adding an All-Day Event from HomeAssistant. The shortfall is that, doing so currently renders the reminders as 1 hour before (23:00) and 1 day before Midnight (00:00).

I'm wanting to add a Reminder Override via Service Call in HA.

This morning I bumped gcal_sync to 4.2.0 and tested. Just one little problem.

Get an error: `Error executing script. Error for call_service at pos 1: Error from API: 400: Cannot specify both default reminders and overrides at the same time.: Bad Request`

HA Object Call:
```
  id=None 
  ical_uuid=None 
  summary='Bowling' 
  start=DateOrDatetime(date=datetime.date(2023, 3, 11), 
  date_time=None, timezone=None) 
  end=DateOrDatetime(date=datetime.date(2023, 3, 12), 
  date_time=None, timezone=None) 
  description='Birthday bowling' 
  location=None 
  transparency='opaque' 
  status=<EventStatusEnum.CONFIRMED: 'confirmed'> 
  event_type=<EventTypeEnum.DEFAULT: 'default'> 
  visibility=<VisibilityEnum.DEFAULT: 'default'> 
  attendees=[] 
  attendees_omitted=False 
  recurrence=[] 
  recur=None 
  recurring_event_id=None 
  original_start_time=None 
  reminders=Reminders(
    use_default=False,
    overrides=[
      ReminderOverride(
        method=<ReminderMethod.POPUP: 'popup'>, 
        minutes=60)])
```

json.loads(event.json(exclude_unset=True, by_alias=True)) parse:
```
{
   "summary":"Bowling",
   "start":{
      "date":"2023-03-11"
   },
   "end":{
      "date":"2023-03-12"
   },
   "description":"Birthday bowling",
   "reminders":{
      "overrides":[
         {
            "method":"popup",
            "minutes":60
         }
      ]
   }
}
```

Notably, `use_default` disappears. Which I believe is the result of `exclude_unset=True`.

model.py update:
`use_default: bool = Field(alias="useDefault", default=**True**)`

**Comment by allenporter** [comment] 2023-04-30 13:18
Thanks, do you want to send a PR to fix? Sounds like the issue is the default...

**Comment by allenporter** [comment] 2023-04-30 13:18
Thanks, do you want to send a PR to fix? Sounds like the issue is the default...
